### ISSUE TITLE
Composer window sizing doesn't work as expected

### ISSUE THREAD

**Issue by Pilvinen** [NodeBB/nodebb-plugin-composer-redactor#62]
It looks like this:
![](https://snag.gy/dA6lsR.jpg)
Which is not normal. When I start typing it stretches as I type. Scrolling doesn't work.

**Comment by frndxyz** [comment]
you can fix it by replacing this line in :  "nodebb-plugin-composer-default/static/lib/composer/resize.js"
 $window.trigger('action:composer.resize',
{
containerHeight : postContainer.height() - 120
});



though its not a proper solution, but scrolling works and editor resize when you put content inside.

**Comment by julianlam** [comment]
Can you reproduce @pitaj?

**Comment by pitaj** [comment]
What browser?

Also, what version of this plugin and NodeBB?

**Comment by pitaj** [comment]
Unable to repro in FF or Chrome

**Comment by frndxyz** [comment]
@pitaj NodeBB V1.4.2, plugin version : 1.4.15

**Comment by pitaj** [comment]
Try `./nodebb stop && ./nodebb build && ./nodebb start`

**Comment by frndxyz** [comment]
@pitaj it doesn't seems to fix the issue.

**Comment by pitaj** [comment]
Is your forum public? I don't think I can diagnose this without direct access to it.

**Comment by julianlam** [comment]
Actually, should be resolved with latest commit to this plugin.

**Comment by Pilvinen** [comment]
You can test it at my forum here: https://foorumit.maailmanloppu.fi

**Comment by Pilvinen** [comment]
I'm still having this issue with Nodebb v1.4.2, Redactor v2.0.1, Chrome 52.0.2743.82 (64-bit). But I highly doubt that it would be browser specific since all my forums users are having the same problem.

https://foorumit.maailmanloppu.fi

**Comment by julianlam** [comment]
Plugin version?

**Comment by Pilvinen** [comment]
Like I said above Redactor v2.0.1

**Comment by pitaj** [comment]
This should be fixed in the latest version. Try updating to v2.0.3

**Comment by Pilvinen** [comment]
Unfortunately this does not seem to be the case. 

1) Updated to v2.0.3.
2) Shut down and restarted Nodebb just to be on the safe side.
3) Still the same issues.

- Does not scroll.
- The editor window is smaller than it's supposed to be.

Screenshot:

![](https://snag.gy/FZ1jxD.jpg)

**Comment by pitaj** [comment]
Did you try the `./nodebb build` thing I suggested before?

**Comment by Pilvinen** [comment]
Yes. It didn't work. But I tried again and did git pull even though there should be no updates and after that ran ./nodebb build again and that did the trick.

It seems to work now. Thank you.
